import Head from "next/head";
import Addbook from "../components/Addbook";
import BookList from "../components/BookList";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Hello first graphql</p>
      <BookList />
      <Addbook />
    </div>
  );
}
